language: ruby
sudo: required
dist: trusty
rvm:
  - "2.1.9"
env:
  - DB=postgresql
addons:
  postgresql: "9.5"
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart
  - cp config/database.yml.travis config/database.yml
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate 
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
branches:
  only:
    - master
    - withoutRailsAdmin
services:
  - postgresql  